#ifndef JCONFIG_H
#define JCONFIG_H

#define JPEG_LIB_VERSION 62
#define LIBJPEG_TURBO_VERSION "4.1.1"
#define LIBJPEG_TURBO_VERSION_NUMBER 4001001
#define C_ARITH_CODING_SUPPORTED 1
#define D_ARITH_CODING_SUPPORTED 1
#define MEM_SRCDST_SUPPORTED 1
#define BITS_IN_JSAMPLE 8

#endif
